### ISSUE TITLE
sanitize.css v6.0.0 反映

### ISSUE THREAD

**Issue by qrac** [qrac/shitajicss#11]
saintize.cssが5日前にv6をリリースしていたので、内容を確認し反映が必要な部分を探す。ぱっと見た感じ、style-lint導入でインデントが変更になっている箇所が多いのと、`dialog`追加、不要な表記の削除が行われているが、大きく変更されてはいないよう。また、所有が個人からcsstoolsというグループに変わった。

- [csstools/sanitize.css: A best-practices CSS foundation](https://github.com/csstools/sanitize.css)

※リリースはまだ発行されていないので、まだ修正があるのかもしれない。発行され次第対応。

**Comment by qrac** [comment]
npmにリリースされているようなので反映していいのかも。

**Comment by qrac** [comment]
sanitize.css 変更点

```scss
// box-sizing: inherit -> border-box;
*,
::before,
::after {
  background-repeat: no-repeat;
  box-sizing: border-box;
}

// Add break-word
html {
  line-height: 1.15;
  cursor: default;
  -ms-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
  word-break: break-word;
}

// Remove border-bottom: none; Firefox 39
abbr[title] {
  text-decoration: underline;
  text-decoration: underline dotted;
}

// Remove color: inherit;
input,
select,
textarea {
  font-family: inherit;
  font-size: inherit;
  line-height: inherit;
}

// Add text-transform: none;
// Remove input tag
button {
  overflow: visible;
  text-transform: none;
}

// Remove html tag
button,
[type="button"],
[type="reset"],
[type="submit"] {
  -webkit-appearance: button;
}

// Remove tag
::-moz-focus-inner {
  border-style: none;
  padding: 0;
}

// Add text-transform: none; Firefox
select {
  text-transform: none;
}

// Remove data
::-webkit-inner-spin-button,
::-webkit-outer-spin-button {
  height: auto;
}

// Remove data, [type="search"]::-webkit-search-cancel-button
::-webkit-search-decoration {
  -webkit-appearance: none;
}

// Add dialog
dialog {
  background-color: white;
  border: solid;
  color: black;
  display: block;
  height: -moz-fit-content;
  height: -webkit-fit-content;
  height: fit-content;
  left: 0;
  margin: auto;
  padding: 1em;
  position: absolute;
  right: 0;
  width: -moz-fit-content;
  width: -webkit-fit-content;
  width: fit-content;
}
dialog:not([open]) {
  display: none;
}

// More Remove = dfn, mark, sub, sup

// More little = `color: #000000;` -> `color: #000;`
```
