### ISSUE TITLE
htmlにword-break付与

### ISSUE THREAD

**Issue by qrac** [qrac/shitajicss#13]
#11 sanitize.css v6.0.0 反映 〜 細分化して検証

- Added: `word-break: break-word` to `html`

```scss
html {
	box-sizing: border-box; /* 1 */
	cursor: default; /* 2 */
	-ms-text-size-adjust: 100%; /* 3 */
	-webkit-text-size-adjust: 100%; /* 3 */
}
```

```scss
// after
html {
  line-height: 1.15; /* 1 */
  cursor: default; /* 2 */
  -ms-text-size-adjust: 100%; /* 3 */
  -webkit-text-size-adjust: 100%; /* 3 */
  word-break: break-word; /* 4 */
}
```
