### ISSUE TITLE
ブラウザ対応状況で不要なタグの除去

### ISSUE THREAD

**Issue by qrac** [qrac/shitajicss#14]
#11 sanitize.css v6.0.0 反映 〜 細分化して検証

- Added: normalize.css updates

```scss
// before
abbr[title] {
	border-bottom: none; /* 1 */
	text-decoration: underline; /* 2 */
	text-decoration: underline dotted; /* 2 */
}
```

```scss
// after
abbr[title] {
  text-decoration: underline;
  text-decoration: underline dotted;
}
```

**Comment by qrac** [comment]
テスト

- [Spot test of sanitize.css v6](https://codepen.io/qrac/pen/RJEveM)

**Comment by qrac** [comment]
Firefox 39

![image](https://user-images.githubusercontent.com/9658016/42120950-4e29557c-7c5f-11e8-9554-740a6f636f8e.png)

Firefox 40

![image](https://user-images.githubusercontent.com/9658016/42120959-6b8315cc-7c5f-11e8-90b7-daf85940bcd9.png)

**Comment by qrac** [comment]
Firefox 39の時にテキストアンダーラインが2重になるようだけど、現行のFirefoxはすでにバージョン61のため問題ない。採用する。

**Comment by qrac** [comment]
```scss
// Remove html tag
button,
[type="button"],
[type="reset"],
[type="submit"] {
  -webkit-appearance: button;
}

// Remove tag
::-moz-focus-inner {
  border-style: none;
  padding: 0;
}

// Remove data
::-webkit-inner-spin-button,
::-webkit-outer-spin-button {
  height: auto;
}

// Remove data, [type="search"]::-webkit-search-cancel-button
::-webkit-search-decoration {
  -webkit-appearance: none;
}

// More Remove = dfn, mark, sub, sup

// More little = `color: #000000;` -> `color: #000;`
```

**Comment by qrac** [comment]
以下もいつの間にか削除されていた。削除しても不具合はなさそう。

```scss
::-webkit-input-placeholder {
  color: inherit;
}
```
