### ISSUE TITLE
form系タグにfont-familyを引き継ぐ

### ISSUE THREAD

**Issue by qrac** [qrac/shitajicss#15]
#11 sanitize.css v6.0.0 反映 〜 細分化して検証

- Added: `font-family: inherit` on form elements

```scss
button,
input,
select,
textarea {
  font-family: inherit;
  font-size: inherit;
  line-height: inherit;
}
```
