### ISSUE TITLE
dialogタグスタイルの共通化

### ISSUE THREAD

**Issue by qrac** [qrac/shitajicss#16]
#11 sanitize.css v6.0.0 反映 〜 細分化して検証

normarize.cssなどには無く、sanitize.cssのみ追加されているが必要？

```scss
dialog {
  background-color: white;
  border: solid;
  color: black;
  display: block;
  height: -moz-fit-content;
  height: -webkit-fit-content;
  height: fit-content;
  left: 0;
  margin: auto;
  padding: 1em;
  position: absolute;
  right: 0;
  width: -moz-fit-content;
  width: -webkit-fit-content;
  width: fit-content;
}

dialog:not([open]) {
  display: none;
}
```
