### ISSUE TITLE
カーソルの非活性プロパティを修正

### ISSUE THREAD

**Issue by qrac** [qrac/shitajicss#21]
![image](https://user-images.githubusercontent.com/9658016/47963479-5c0b3f00-e070-11e8-8f5e-c7231bff45d4.png)

- [cursor - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/cursor)
- [【CSS】cursorの使い方：カーソル形状の変え方と値一覧](https://saruwakakun.com/html-css/basic/cursor)

ボタンなどが非活性の場合は `not-allowed` で禁止を表す方が伝わりやすいのでは。

## Before

```scss
[aria-disabled] {
  cursor: default;
}
```

## After

```scss
[aria-disabled="true"],
[disabled] {
  cursor: not-allowed;
}
```
