### ISSUE TITLE
フォーム要素への文字色引き継ぎ

### ISSUE THREAD

**Issue by qrac** [qrac/shitajicss#22]
`body` の文字色が `#000` 以外の場合（※ここでは確認のためわかりやすい `red` を指定）

## Before

![image](https://user-images.githubusercontent.com/9658016/47973188-7253e200-e0e6-11e8-8aaa-24fd3c831bad.png)

`button` `input` `select` `textarea` は文字色に `body` の色が引き継がれず、CSSデザインで毎回修正する必要がある。フォーム要素だけ文字色が真っ黒となる場合がほとんど。

## After

![image](https://user-images.githubusercontent.com/9658016/47973249-ca8ae400-e0e6-11e8-8e35-7f934592b522.png)

`inherit` を設定することで回避できる。

```scss
button,
input,
select,
textarea {
    color: inherit;
}
```
