### ISSUE TITLE
絵文字の指定は不要？

### ISSUE THREAD

**Issue by qrac** [qrac/shitajicss#23]
sanitize.css v8.0.0のフォントファミリー指定にemojiがある。ここまで書く必要はある？Issueが上がっていなかったので追加された文脈が不明。

- [sanitize.css/sanitize.css at master · csstools/sanitize.css](https://github.com/csstools/sanitize.css/blob/master/sanitize.css)

```scss
html {
  cursor: default; /* 1 */
  font-family:
    system-ui,
    /* macOS 10.11-10.12 */ -apple-system,
    /* Windows 6+ */ Segoe UI,
    /* Android 4+ */ Roboto,
    /* Ubuntu 10.10+ */ Ubuntu,
    /* Gnome 3+ */ Cantarell,
    /* KDE Plasma 5+ */ Noto Sans,
    /* fallback */ sans-serif,
    /* macOS emoji */ "Apple Color Emoji",
    /* Windows emoji */ "Segoe UI Emoji",
    /* Windows emoji */ "Segoe UI Symbol",
    /* Linux emoji */ "Noto Color Emoji"; /* 2 */
  line-height: 1.15; /* 3 */
  -moz-tab-size: 4; /* 4 */
  tab-size: 4; /* 4 */
  -ms-text-size-adjust: 100%; /* 5 */
  -webkit-text-size-adjust: 100%; /* 5 */
  word-break: break-word; /* 6 */
}
```
