### ISSUE TITLE
リセット内容を最新ブラウザで目視した最小限のものに縮小

### ISSUE THREAD

**Issue by qrac** [qrac/shitajicss#31]
sanitize.cssなどの参照を終了。自分が最新ブラウザで目視したものだけを記載。影響がみられないCSSは削除。

**Comment by qrac** [comment]
テキストレンダリングに関する設定を削除。

```css
body {
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```
