### ISSUE TITLE
addressの斜体をリセット

### ISSUE THREAD

**Issue by qrac** [qrac/shitajicss#6]
addressタグを使うとブラウザCSSでitalicになったりするので、リセットしたほうがいいかも。

```scss
address {
  font-style: normal;
}
```

または

```scss
*,
:after,
:before {
    font-style: inherit;
}
```

などを検討。

**Comment by qrac** [comment]
[Introduction · Bootstrap](https://v4-alpha.getbootstrap.com/getting-started/introduction/)

```scss
address {
    margin-bottom: 1rem;
    font-style: normal;
    line-height: inherit;
}
```

[Material Design Lite](https://getmdl.io/components/index.html)

```scss
address {
    font-size: 12px;
    line-height: 1;
    font-style: normal;
}
```

**Comment by qrac** [comment]
addressを個別にリセットする場合が多いようなので、以下を採用。

```scss
address {
  font-style: normal;
}
```
